
### Get all reswtaurants
GET http://localhost:8000/restaurants

### Get all reswtaurants filter cuisine
GET http://localhost:8000/restaurants?cuisine=FastFood

### Get restaurant by id
GET http://localhost:8000/restaurants/3

### Post restaurant
POST http://localhost:8000/restaurants
Content-Type: application/json

{
  "name": "KFC",
  "isKosher": false,
  "cuisines": ["Fast Food", "American"]
}

### Update restaurant
PUT http://localhost:8000/restaurants/4
Content-Type: application/json

{
  "cuisines": [ "Fast   Food","American"]
}

### Delete restaurant
DELETE http://localhost:8000/restaurants/1
```
